'use client';
import { FormEvent, ReactNode, useEffect, useState } from 'react';
import { browserSupabase } from '@/lib/client-auth';

export default function AuthGate({ children }: { children: ReactNode }) {
  const [ready, setReady] = useState(false); const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState('');
  useEffect(() => { browserSupabase.auth.getSession().then(({ data }) => { setReady(Boolean(data.session)); }); const { data: listener } = browserSupabase.auth.onAuthStateChange((_event, session) => setReady(Boolean(session))); return () => listener.subscription.unsubscribe(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); const { error } = await browserSupabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/` } }); if (error) setError('Не вдалося надіслати лист. Спробуйте пізніше.'); else setSent(true); };
  if (ready) return <>{children}</>;
  return <main className="max-w-[680px] mx-auto px-5 py-16 min-h-[calc(100vh-56px)] flex items-center"><section className="w-full bg-white rounded-2xl shadow-soft border border-vivat-light p-7 md:p-10"><p className="text-vivat-accent text-sm font-semibold tracking-wide uppercase mb-3">Безпечний доступ</p><h1 className="text-[32px] font-bold tracking-tight text-vivat-dark mb-3">Порівнюйте ціни на книжки</h1><p className="text-gray-500 mb-8">Створіть безкоштовний акаунт. Ми надішлемо одноразове посилання для входу — паролі не потрібні.</p>{sent ? <p className="rounded-xl bg-vivat-light p-4 text-vivat-dark">Перевірте пошту та відкрийте посилання для входу.</p> : <form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium text-vivat-dark">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-vivat" placeholder="you@example.com" /></label>{error && <p className="text-sm text-red-600">{error}</p>}<button className="w-full rounded-xl bg-vivat px-4 py-3 font-semibold text-white transition hover:bg-vivat-dark">Надіслати посилання для входу</button></form>}<p className="mt-6 text-xs text-gray-400">Безкоштовний доступ має обмеження на живі пошуки, щоб сервіс залишався доступним усім.</p></section></main>;
}
