'use client';
import { FormEvent, ReactNode, useEffect, useState } from 'react';

type Mode = 'sign-in' | 'sign-up';
function signUpError(message: string) { const value = message.toLowerCase(); if (value.includes('email rate limit')) return 'Забагато листів підтвердження. Зачекайте кілька хвилин.'; if (value.includes('email') && (value.includes('send') || value.includes('smtp'))) return 'Не вдалося надіслати лист підтвердження. Перевірте Email provider / SMTP у Supabase.'; if (value.includes('password')) return `Пароль відхилено: ${message}`; return `Помилка реєстрації: ${message}`; }

export default function AuthGate({ children }: { children: ReactNode }) {
  const [ready, setReady] = useState<boolean | null>(null); const [mode, setMode] = useState<Mode>('sign-in'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
  useEffect(() => { fetch('/api/auth/session').then((response) => response.json()).then((data) => setReady(Boolean(data.authenticated))).catch(() => setReady(false)); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setNotice(''); if (mode === 'sign-up' && password.length < 8) { setError('Пароль має містити щонайменше 8 символів.'); return; } setPending(true); try { const response = await fetch(`/api/auth/${mode === 'sign-up' ? 'sign-up' : 'sign-in'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) { setError(mode === 'sign-up' ? signUpError(data.error || 'Unknown error') : 'Неправильний email або пароль.'); return; } if (data.requiresConfirmation) { setNotice('Акаунт створено. Підтвердьте email у листі, щоб увійти.'); return; } setReady(true); } catch { setError('Не вдалося підключитися. Спробуйте ще раз.'); } finally { setPending(false); } };
  if (ready) return <>{children}</>;
  if (ready === null) return <main className="max-w-[680px] mx-auto px-5 py-16 min-h-[calc(100vh-56px)]" />;
  return <main className="w-full min-w-0 max-w-[680px] mx-auto px-4 sm:px-5 py-12 sm:py-16 min-h-[calc(100vh-56px)] flex items-center"><section className="w-full min-w-0 bg-white rounded-2xl shadow-soft border border-vivat-light p-5 sm:p-7 md:p-10"><p className="text-vivat-accent text-sm font-semibold tracking-wide uppercase mb-3">Безпечний доступ</p><h1 className="text-[32px] font-bold tracking-tight text-vivat-dark mb-3">Порівнюйте ціни на книжки</h1><p className="text-gray-500 mb-6">Створіть безкоштовний акаунт або увійдіть. Сеанс захищений і зберігається лише в браузерній cookie.</p><div className="grid grid-cols-2 gap-2 mb-6">{([{ key: 'sign-in', label: 'Увійти' }, { key: 'sign-up', label: 'Реєстрація' }] as const).map((tab) => <button type="button" key={tab.key} onClick={() => { setMode(tab.key); setError(''); setNotice(''); }} className={`min-w-0 rounded-xl px-3 py-2 font-medium ${mode === tab.key ? 'bg-vivat text-white' : 'bg-vivat-light text-vivat-dark'}`}>{tab.label}</button>)}</div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium text-vivat-dark">Email<input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full min-w-0 rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-vivat" placeholder="you@example.com" /></label><label className="block text-sm font-medium text-vivat-dark">Пароль<input required minLength={mode === 'sign-up' ? 8 : undefined} type="password" autoComplete={mode === 'sign-up' ? 'new-password' : 'current-password'} value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full min-w-0 rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-vivat" placeholder={mode === 'sign-up' ? 'Щонайменше 8 символів' : 'Ваш пароль'} /></label>{error && <p className="break-words text-sm text-red-600">{error}</p>}{notice && <p className="rounded-xl bg-vivat-light p-4 text-sm text-vivat-dark">{notice}</p>}<button disabled={pending} className="w-full rounded-xl bg-vivat px-4 py-3 font-semibold text-white transition hover:bg-vivat-dark disabled:opacity-60">{pending ? 'Зачекайте…' : mode === 'sign-up' ? 'Створити акаунт' : 'Увійти'}</button></form><p className="mt-6 text-xs text-gray-400">Безкоштовний доступ має обмеження на живі пошуки, щоб сервіс залишався доступним усім.</p></section></main>;
}
