'use client';
import { FormEvent, useState } from 'react';
import { authHeaders } from '@/lib/client-auth';

export default function FeedbackPage() {
  const [message, setMessage] = useState(''); const [state, setState] = useState<'idle'|'sent'|'error'>('idle');
  const submit = async (event: FormEvent) => { event.preventDefault(); setState('idle'); const response = await fetch('/api/bug-reports', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(await authHeaders()) }, body: JSON.stringify({ message, page: window.location.href }) }); if (response.ok) { setMessage(''); setState('sent'); } else setState('error'); };
  return <div className="max-w-lg"><div className="border-b border-vivat-light pb-6"><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.16em] text-vivat-accent">Зворотний звʼязок</p><h1 className="font-book text-[40px] font-bold leading-none tracking-[-0.05em] text-vivat-dark">Повідомити про проблему</h1></div><p className="mb-7 mt-5 text-[15px] leading-6 text-gray-500">Напишіть, що сталося і яку книжку ви шукали. Це повідомлення потрапить до технічного журналу.</p><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium text-vivat-dark">Ваше повідомлення<textarea required minLength={10} maxLength={4000} value={message} onChange={(event) => setMessage(event.target.value)} className="mt-2 min-h-40 w-full resize-y rounded-xl border border-vivat-light bg-white p-4 outline-none transition focus:border-vivat" placeholder="Наприклад: ціна в магазині відрізняється від вказаної на сайті…" /></label><button className="rounded-xl bg-vivat px-5 py-3 font-semibold text-white transition hover:bg-vivat-dark">Надіслати повідомлення</button>{state==='sent'&&<p className="border-l-2 border-vivat-accent pl-3 text-sm text-vivat">Повідомлення надіслано. Дякуємо.</p>}{state==='error'&&<p className="border-l-2 border-red-500 pl-3 text-sm text-red-700">Не вдалося надіслати повідомлення. Спробуйте ще раз.</p>}</form></div>;
}
